swagger: "2.0"
info:
  description: "Epic Road Trip Swagger documentation for endpoints and models"
  version: "1.0.1"
  title: "Epic Road Trip Swagger Doc"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "johan-david.dehi@epitech.eu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "epicroadtripapi.herokuapp.com"
basePath: "/swagger"
tags:
  - name: "User"
    description: "Operations about User"
  - name: "Search"
    description: "Operations about Search"
  - name: "Roadtrip"
    description: "Operations about Roadtrip"
  - name: "Payment"
    description: "Operations about Payment"
schemes:
  - "https"
paths:
  /users/login:
    post:
      tags:
        - "User"
      summary: "User login"
      description: "This is a description"
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          schema:
            $ref: "#/definitions/LoginBody"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/LoginResponse"
        "401":
          description: "Unauthorized - Invalid email or password"
        "500":
          description: "Internal server error"
  /users/{page}&{limit}:
    get:
      tags:
        - "User"
      summary: "Get all users"
      description: "This is a description"
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "page"
          in: "path"
          description: "Number of pages"
          required: true
          type: "string"
        - name: "limit"
          in: "path"
          description: "Item per page"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/UserResponse"
        "500":
          description: "Internal server error"
  /users:
    post:
      tags:
        - "User"
      summary: "Create a user"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          schema:
            $ref: "#/definitions/User"
      responses:
        "201":
          description: "Successful operation"
        "500":
          description: "Internal server error"
  /users/{id}:
    put:
      tags:
        - "User"
      summary: "Update a user"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "User id"
          required: true
          type: "string"
          format: "ObjectId"
        - in: "body"
          name: "body"
          description: ""
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/UserResponse"
        "500":
          description: "Internal server error"
    delete:
      tags:
        - "User"
      summary: "Delete a user"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "User id"
          required: true
          type: "string"
          format: "ObjectId"
      responses:
        "200":
          description: "Successful operation"
        "500":
          description: "Internal server error"
  /users/{id}/favorites:
    put:
      tags:
        - "User"
      summary: "Update a user's favorites"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "User id"
          required: true
          type: "string"
          format: "ObjectId"
        - in: "body"
          name: "body"
          description: ""
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/UserResponse"
        "500":
          description: "Internal server error"
  /payment/session:
    post:
      tags:
        - "User"
      summary: "Generate Stripe session ID to validate checkout"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "201":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/PaymentResponse"
        "500":
          description: "Internal server error"
  /search/eat/{latitude}&{longitude}&{distance}&{rating}:
    get:
      tags:
        - "Search"
      summary: "Get informations about restaurants (Rapid API)"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "latitude"
          in: "path"
          description: "Lat params"
          required: true
          type: "string"
        - name: "longitude"
          in: "path"
          description: "Lng params"
          required: true
          type: "string"
        - name: "distance"
          in: "path"
          description: "Distance radius params"
          type: "string"
          required: true
        - name: "rating"
          in: "path"
          description: "Rating params"
          type: "string"
          required: true
      responses:
        "200":
          description: "Successful operation"
        "500":
          description: "Internal server error"
  /search/drink/{latitude}&{longitude}&{distance}:
    get:
      tags:
        - "Search"
      summary: "Get informations about a location (Rapid API)"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "latitude"
          in: "path"
          description: "Lat params"
          required: true
          type: "string"
        - name: "longitude"
          in: "path"
          description: "Lng params"
          required: true
          type: "string"
        - name: "distance"
          in: "path"
          description: "Distance radius params"
          type: "string"
          required: true
      responses:
        "200":
          description: "Successful operation"
        "500":
          description: "Internal server error"
  /search/sleep/{latitude}&{longitude}&{checkIn}:
    get:
      tags:
        - "Search"
      summary: "Get informations about hotels (Travel API)"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "latitude"
          in: "path"
          description: "Lat params"
          required: true
          type: "string"
        - name: "longitude"
          in: "path"
          description: "Lng params"
          required: true
          type: "string"
        - name: "checkIn"
          in: "path"
          description: "Check-in date params"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful operation"
        "500":
          description: "Internal server error"
  /search/enjoy/{latitude}&{longitude}&{distance}:
    get:
      tags:
        - "Search"
      summary: "Get informations about activities (Google Places API)"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "latitude"
          in: "path"
          description: "Lat params"
          required: true
          type: "string"
        - name: "longitude"
          in: "path"
          description: "Lng params"
          required: true
          type: "string"
        - name: "distance"
          in: "path"
          description: "Distance radius params"
          type: "string"
          required: true
      responses:
        "200":
          description: "Successful operation"
        "500":
          description: "Internal server error"
  /search/travel/{name}:
    get:
      tags:
        - "Search"
      summary: "Get informations about transportation (Travel / Rapid API)"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: "path"
          description: "Destination name params"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful operation"
        "500":
          description: "Internal server error"
  /roadtrips/{user}:
    get:
      tags:
        - "Roadtrip"
      summary: "Get user's roadtrip(s)"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "user"
          in: "path"
          description: "User ID params"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful operation"
        "500":
          description: "Internal server error"
  /roadtrips:
    post:
      tags:
        - "Roadtrip"
      summary: "Create a roadtrip"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "201":
          description: "Successful operation"
        "500":
          description: "Internal server error"
  /payment/*session:
    post:
      tags:
        - "Payment"
      summary: "Create a payment session (cart)"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "201":
          description: "Successful operation"
        "500":
          description: "Internal server error"
  /payment/*request:
    post:
      tags:
        - "Payment"
      summary: "Create a roadtrip"
      description: ""
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "201":
          description: "Successful operation"
        "500":
          description: "Internal server error"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "string"
        format: "ObjectId"
      email:
        type: "string"
      login:
        type: "string"
      password:
        type: "string"
      isAdmin:
        type: "boolean"
        default: false
      registrationDate:
        type: "string"
        format: "date-time"
        default: "NOW()"
      providers.googleId:
        type: "string"
      providers.facebookId:
        type: "string"
      roadtrips:
        type: "array"
        items:
          $ref: "#/definitions/RoadTrip"
  RoadTrip:
    type: "object"
    properties:
      id:
        type: "string"
        format: "ObjectId"
      name:
        type: "string"
      destinations:
        type: "array"
        items:
          $ref: "#/definitions/Destination"
  Destination:
    type: "object"
    properties:
      id:
        type: "string"
        format: "ObjectId"
      city:
        type: "string"
      latitude:
        type: "string"
      longitude:
        type: "string"
      activities:
        type: "array"
        items:
          $ref: "#/definitions/Activity"
  Activity:
    type: "object"
    properties:
      id:
        type: "string"
        format: "ObjectId"
      name:
        type: "string"
      price:
        type: "string"
      date:
        type: "string"
        format: "date-time"
      rate:
        type: "string"
      latitude:
        type: "string"
      longitude:
        type: "string"
  PaymentResponse:
    type: "object"
    properties:
      session:
        type: "string"
  UserResponse:
    type: "object"
    properties:
      email:
        type: "string"
      login:
        type: "string"
      isAdmin:
        type: "boolean"
      registrationDate:
        type: "string"
        format: "date-time"
  LoginBody:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
  FacebookLoginBody:
    type: "object"
    properties:
      email:
        type: "string"
      login:
        type: "string"
      id:
        type: "string"
  GoogleLoginBody:
    type: "object"
    properties:
      email:
        type: "string"
      login:
        type: "string"
      id:
        type: "string"

  LoginResponse:
    type: "object"
    properties:
      authorization:
        type: "string"
        format: "jwt"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"