/* USER ACTIONS */
export const LOADING_USER = "LOADING_USER";
export const ERROR_USER = "ERROR_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const AUTH_FACEBOOK_SUCCESS = "AUTH_FACEBOOK_SUCCESS";
export const AUTH_GOOGLE_SUCCESS = "AUTH_GOOGLE_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

/* PAYMENT ACTIONS */
export const LOADING_PAYMENT = "LOADING_PAYMENT";
export const ERROR_PAYMENT = "ERROR_PAYMENT";
export const VALIDATE_PAYMENT_SUCCESS = "VALIDATE_PAYMENT_SUCCESS";
export const CANCEL_PAYMENT_SUCCESS = "CANCEL_PAYMENT_SUCCESS";

/* ROADTRIP ACTIONS */
export const LOADING_ROADTRIP = "LOADING_ROADTRIP";
export const ERROR_ROADTRIP = "ERROR_ROADTRIP";
export const UPDATE_DEPARTURE_ARRIVAL_SUCCESS = "UPDATE_DEPARTURE_ARRIVAL_SUCCESS";
export const UPDATE_STEP_SUCCESS = "UPDATE_STEP_SUCCESS";
export const ADD_ESCALE_SUCCESS = "ADD_ESCALE_SUCCESS";
export const GET_EAT_SUCCESS = "GET_EAT_SUCCESS";
export const GET_DRINK_SUCCESS = "GET_DRINK_SUCCESS";
export const GET_SLEEP_SUCCESS = "GET_SLEEP_SUCCESS";
export const GET_TRAVEL_SUCCESS = "GET_TRAVEL_SUCCESS";
export const GET_ENJOY_SUCCESS = "GET_ENJOY_SUCCESS";
export const UPDATE_FILTER_DIALOG_SUCCESS = "UPDATE_FILTER_DIALOG_SUCCESS";
export const UPDATE_DETAILS_DIALOG_SUCCESS = "UPDATE_DETAILS_DIALOG_SUCCESS";
export const UPDATE_CURRENT_STEP_SUCCESS = "UPDATE_CURRENT_STEP_SUCCESS";
export const GET_RESEARCH_SUCCESS = "GET_RESEARCH_SUCCESS";
export const UPDATE_FAVORITE_SELECTED_SUCCESS = "UPDATE_FAVORITE_SELECTED_SUCCESS";
export const UPDATE_FAVORITES_SUCCESS = "UPDATE_FAVORITES_SUCCESS";
export const UPDATE_ROADTRIP_NAME_SUCCESS = "UPDATE_ROADTRIP_NAME_SUCCESS";
export const ADD_ROADTRIP_ACTIVITY_SUCCESS = "ADD_ROADTRIP_ACTIVITY_SUCCESS";
export const CREATE_ROADTRIP_SUCCESS = "CREATE_ROADTRIP_SUCCESS";
export const GET_ROADTRIP_SUCCESS = "GET_ROADTRIP_SUCCESS";
export const UPDATE_FILTER_SUCCESS = "UPDATE_FILTER_SUCCESS";